### ISSUE TITLE
Reproducibility of incast scenario

### ISSUE THREAD

**Issue by hrezae2** [PlatformLab/HomaTransport#10]
Hi @behnamm!

Can you please help me with running a scenario of Homa while multiple senders are sending messages to a single machine simultaneously? Based on figure 10 in the Homa paper, I believe you did such a simulation but I was not able to find it. Many thanks in advance!

**Comment by behnamm** [comment]
Hi,
If you mean figure 10 of the complete paper on arxiv (the incast experiment), that figure was generated from real system implementation of Homa; you probably wont be able to generate that graph using the Homa simulator. If you mean figure 10 of the shorter SIGCOMM paper, that graph is generated from an all-to-all traffic pattern using the simulator, but you shouldn't expect  to generate that graph from an incast pattern.

**Comment by hrezae2** [comment]
@behnamm Yes, I meant figure 10 of the arxiv paper. I will try to simulate incast on the OMNET++ version. I am a NS3 person so I might need to spend some time on it. Anyways, thank you for your help.
