### ISSUE TITLE
Unable to build Homa

### ISSUE THREAD

**Issue by redtagsolution** [PlatformLab/HomaTransport#6]
Hi,

I am unable to build Homa, getting following error. Can you please look into it and respond?

common/GlobalSignalListener.cc: In member function 'void GlobalSignalListener::handleMesgStatsObj(cObject*)':
common/GlobalSignalListener.cc:83:43: error: call of overloaded 'emit(simsignal_t&, uint64_t&)' is ambiguous
     emit(bytesOnWireSignal, mesgSizeOnWire);
                                           ^
common/GlobalSignalListener.cc:83:43: note: candidates are:
In file included from C:/Users/muham/omnetpp-4.6/include/omnetpp.h:26:0,
                 from common/GlobalSignalListener.h:23,
                 from common/GlobalSignalListener.cc:17:
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:419:10: note: void cComponent::emit(simsignal_t, bool)
     void emit(simsignal_t signalID, bool b);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:426:10: note: void cComponent::emit(simsignal_t, long int)
     void emit(simsignal_t signalID, long l);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:433:10: note: void cComponent::emit(simsignal_t, long unsigned int)
     void emit(simsignal_t signalID, unsigned long l);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:440:10: note: void cComponent::emit(simsignal_t, double)
     void emit(simsignal_t signalID, double d);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:451:10: note: void cComponent::emit(simsignal_t, const SimTime&)
     void emit(simsignal_t signalID, const SimTime& t);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:458:10: note: void cComponent::emit(simsignal_t, const char*) <near match>
     void emit(simsignal_t signalID, const char *s);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:458:10: note:   no known conversion for argument 2 from 'uint64_t {aka long long unsigned int}' to 'const char*'
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:465:10: note: void cComponent::emit(simsignal_t, cObject*) <near match>
     void emit(simsignal_t signalID, cObject *obj);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:465:10: note:   no known conversion for argument 2 from 'uint64_t {aka long long unsigned int}' to 'cObject*'
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:468:10: note: void cComponent::emit(simsignal_t, const cObject*) <near match>
     void emit(simsignal_t signalID, const cObject *obj) { emit(signalID, const_cast<cObject *>(obj)); }
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:468:10: note:   no known conversion for argument 2 from 'uint64_t {aka long long unsigned int}' to 'const cObject*'
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:471:10: note: void cComponent::emit(simsignal_t, char)
     void emit(simsignal_t signalID, char c) {emit(signalID,(long)c);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:474:10: note: void cComponent::emit(simsignal_t, unsigned char)
     void emit(simsignal_t signalID, unsigned char c) {emit(signalID,(unsigned long)c);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:477:10: note: void cComponent::emit(simsignal_t, short int)
     void emit(simsignal_t signalID, short i) {emit(signalID,(long)i);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:480:10: note: void cComponent::emit(simsignal_t, short unsigned int)
     void emit(simsignal_t signalID, unsigned short i) {emit(signalID,(unsigned long)i);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:483:10: note: void cComponent::emit(simsignal_t, int)
     void emit(simsignal_t signalID, int i) {emit(signalID,(long)i);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:486:10: note: void cComponent::emit(simsignal_t, unsigned int)
     void emit(simsignal_t signalID, unsigned int i) {emit(signalID,(unsigned long)i);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:489:10: note: void cComponent::emit(simsignal_t, float)
     void emit(simsignal_t signalID, float f) {emit(signalID,(double)f);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:492:10: note: void cComponent::emit(simsignal_t, long double)
     void emit(simsignal_t signalID, long double d) {emit(signalID,(double)d);}
          ^
common/GlobalSignalListener.cc:157:64: error: call of overloaded 'emit(std::unordered_map<long long unsigned int, int>::mapped_type&, uint64_t&)' is ambiguous
     emit(mesgBytesOnWireSignals.at(mesgSizeBin), mesgSizeOnWire);
                                                                ^
common/GlobalSignalListener.cc:157:64: note: candidates are:
In file included from C:/Users/muham/omnetpp-4.6/include/omnetpp.h:26:0,
                 from common/GlobalSignalListener.h:23,
                 from common/GlobalSignalListener.cc:17:
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:419:10: note: void cComponent::emit(simsignal_t, bool)
     void emit(simsignal_t signalID, bool b);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:426:10: note: void cComponent::emit(simsignal_t, long int)
     void emit(simsignal_t signalID, long l);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:433:10: note: void cComponent::emit(simsignal_t, long unsigned int)
     void emit(simsignal_t signalID, unsigned long l);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:440:10: note: void cComponent::emit(simsignal_t, double)
     void emit(simsignal_t signalID, double d);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:451:10: note: void cComponent::emit(simsignal_t, const SimTime&)
     void emit(simsignal_t signalID, const SimTime& t);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:458:10: note: void cComponent::emit(simsignal_t, const char*) <near match>
     void emit(simsignal_t signalID, const char *s);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:458:10: note:   no known conversion for argument 2 from 'uint64_t {aka long long unsigned int}' to 'const char*'
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:465:10: note: void cComponent::emit(simsignal_t, cObject*) <near match>
     void emit(simsignal_t signalID, cObject *obj);
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:465:10: note:   no known conversion for argument 2 from 'uint64_t {aka long long unsigned int}' to 'cObject*'
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:468:10: note: void cComponent::emit(simsignal_t, const cObject*) <near match>
     void emit(simsignal_t signalID, const cObject *obj) { emit(signalID, const_cast<cObject *>(obj)); }
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:468:10: note:   no known conversion for argument 2 from 'uint64_t {aka long long unsigned int}' to 'const cObject*'
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:471:10: note: void cComponent::emit(simsignal_t, char)
     void emit(simsignal_t signalID, char c) {emit(signalID,(long)c);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:474:10: note: void cComponent::emit(simsignal_t, unsigned char)
     void emit(simsignal_t signalID, unsigned char c) {emit(signalID,(unsigned long)c);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:477:10: note: void cComponent::emit(simsignal_t, short int)
     void emit(simsignal_t signalID, short i) {emit(signalID,(long)i);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:480:10: note: void cComponent::emit(simsignal_t, short unsigned int)
     void emit(simsignal_t signalID, unsigned short i) {emit(signalID,(unsigned long)i);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:483:10: note: void cComponent::emit(simsignal_t, int)
     void emit(simsignal_t signalID, int i) {emit(signalID,(long)i);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:486:10: note: void cComponent::emit(simsignal_t, unsigned int)
     void emit(simsignal_t signalID, unsigned int i) {emit(signalID,(unsigned long)i);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:489:10: note: void cComponent::emit(simsignal_t, float)
     void emit(simsignal_t signalID, float f) {emit(signalID,(double)f);}
          ^
C:/Users/muham/omnetpp-4.6/include/ccomponent.h:492:10: note: void cComponent::emit(simsignal_t, long double)
     void emit(simsignal_t signalID, long double d) {emit(signalID,(double)d);}
          ^
Makefile:121: recipe for target '../out/gcc-debug/src/common/GlobalSignalListener.o' failed
make[1]: *** [../out/gcc-debug/src/common/GlobalSignalListener.o] Error 1
make[1]: Leaving directory '/c/Users/muham/omnetpp-4.6/samples/RpcTransportDesign/OMNeT++Simulation/homatransport/src'
make: *** [all] Error 2
Makefile:3: recipe for target 'all' failed

**Comment by redtagsolution** [comment]
@behnamm Can you please help?

**Comment by behnamm** [comment]
Have you followed the instructions on the link below? https://github.com/PlatformLab/HomaSimulation/tree/omnet_simulations/RpcTransportDesign/OMNeT%2B%2BSimulation

If yes, which of the steps have you successfully executed?

**Comment by redtagsolution** [comment]
Hi @behnamm , 

Thank you for responding back. Yes I am following the readme.

1 - Install omnet++ version 4.6 under the directory ./omnetpp-4.6/ **(DONE)**

2 - Copy the diff patch below into a file and apply it to OMNeT++ directory and rebuild OMNeT++ from the directory. **(DONE)**

3 - Enter inet/ directory and build inet framework. (I have tried building this, but its not working so I have downloaded inet 3.3.0 and have build that, and then replaced the folder with the one I downloaded in Homa). After that when I tried to build, it was asking for some files which were not present in that inet folder so I manually placed the required files back.

4 - Enter homatransport directory and build homatransport executable file (This is giving me error)

**Comment by behnamm** [comment]
I just cloned the repo myself on a brand new machine with gcc8.2 and Debian10 and installed the whole simulator without any problems.

The 3rd step could be the issue; the inet in the repo is inet2.99.0 but you have replaced it with 3.3. which can cause issues. Make sure you are using the same versions as described in the README and provided in the repo, otherwise you'll run into issues that I won't be able to help.  

Moreover, are you building on a windows machine? If so, I'm afraid I wont be much of help since I have no experience building the simulator on a windows machine.

**Comment by redtagsolution** [comment]
Yes, I am running the code on a Windows machine, and have you been able to build that inet framework in this repo? or just downloaded a new 2.99 version?

I guess, I'll have to try it on my mac. Thank you once again for getting back to me. 

In case, I still find errors I'll drop by another comment here.

**Comment by redtagsolution** [comment]
Hi @behnamm , 

If you can take sometime out, can we get on call and answer some of my questions. I am trying to revamp the code to work with the latest versions of gcc and Debian. A session with you can really pace up things. 

Thanks,
Redtag
