### ISSUE TITLE
Simulation run in command line

### ISSUE THREAD

**Issue by mustansarsaeed** [PlatformLab/HomaTransport#7]
Hi, I have run simulation as you suggested in the ReadMe file in commandline, its been more than 20 hours and its still showing 0%. Does this depend on hard ware? I am running in virtualbox ubuntu. I am assuming that when this simulation will complete then I will be able to use result files to produce the graphs presented in the paper. Please comment.

**Comment by hrezae2** [comment]
@mustansarsaeed were you able to solve this issue? For me it remains like 0% completed even after several days.

**Comment by mustansarsaeed** [comment]
@hrezae2 You need to run this on cloud lab cluster and use the same system / network capacities for producing the same results.

**Comment by hrezae2** [comment]
@mustansarsaeed Thanks Mustansar. So you mean I cannot run it on my VM? I've designed my own scenario and I want the result of that experiment only.

**Comment by behnamm** [comment]
Hello all,
The default time limit of the simulator is set 100s (https://github.com/PlatformLab/HomaSimulation/blob/ab09ecbf2c61b07271a1d797ff34ef3bacdbe723/RpcTransportDesign/OMNeT%2B%2BSimulation/homatransport/src/dcntopo/homaTransportConfig.ini#L7) which practically means infinity considering how long it would take for the simulation to finish. Set the the value to some reasonable number like 100ms or at most 1s, in which case you'd still expect the simulation to run for maybe a few days to finish. Hope that's useful. Good luck.

**Comment by hrezae2** [comment]
@behnamm Thank you very much Behnam. That definitely helps. I have one last question. I don't understand the "-r 6" flag in the sample command that you shared. In the other words, what is number 6 in WorkloadHadoop? Many thanks in advance.
